server:
  port: 32000
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/employee/**
      - id: department-service
        uri: lb://department-service
        predicates:
          - Path=/api/department/**
               
              
